<div class="preview-block">

<?php if ($this->heading): ?>
<h2><?php echo $this->heading; ?></h2>
<?php endif; ?>

<ul class="resource-list preview">
<?php
$headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
$bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');

foreach ($this->resources as $resource):
    $heading = $resource->value($headingTerm, ['default' => $this->translate('[Untitled]')]);
    $bodyTermValue = $resource->value($bodyTerm);
    $bodyResource = $bodyTermValue ? $bodyTermValue->valueResource() : null;
    $body = ($bodyTermValue && $bodyResource) ? $bodyResource->displayTitle() : $bodyTermValue;
?>
    <li class="item resource">
        <?php if ($primaryMedia = $resource->primaryMedia()): ?>
        <?php echo $resource->linkRaw($this->thumbnail($primaryMedia, 'medium')); ?>
        <?php endif; ?>
        <h4><?php echo $resource->link($heading); ?></h4>
        <?php if ($body): ?>
        <div class="description"><?php echo $body;?></div>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>
<p>
<?php
$linkText = $this->linkText == '' ? $this->translate('Browse all') : $this->linkText;
echo $this->hyperlink($linkText, $this->url(
    'site/resource', ['controller' => 'item', 'action' => 'browse'], ['query' => $this->query], true
), ['class' => 'button']);
?>
</p>

</div>
